  # GET http://localhost:4000/users


# POST http://localhost:4000/users
# Content-Type: application/json

# {
#   "name": "aiacai",
#   "password": "123456Chy!"
# }


POST http://localhost:4000/users/login
Content-Type:application/json

{
  "name": "aiacai",
  "password": "123456Chy!"
}



POST http://localhost:4000/users/token
Content-Type:application/json

{
  "name": "aiacai",
  "password": "123456Chy!"
} 